kind: Service
apiVersion: v1
metadata:
  name: docs
  namespace: pyops-docs  # Sets Namespace
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: docs
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
